### ISSUE TITLE
ModelNet

### ISSUE THREAD

**Issue by MartinSmeyer** [wangg12/mx-DeepIM#2]
For usage with ModelNet, some code is still missing. 
Like in lib/dataset/ and the corresponding config.
If you find the time, it would be great if you could add the missing parts.

**Comment by wangg12** [comment]
ModelNet_v1.py is in lib/dataset.

I've added two configs of ModelNet. Since the API has been refactored from our old code, you might need to modify some code to make it work. The hyper-parameters are basically the same as that of the LINEMOD.

Feel free to modify the code to make it work and let me know what modifications are needed to be done. Hope this will help you.

**Comment by dmasmont** [comment]
Hello @wangg12 ,
Which version of MeshLab did you use? I am having trouble to load ModelNet .ogg files

**Comment by wangg12** [comment]
@dmasmont I am using the meshlab installed via `apt-get` on Ubuntu 16.04.
```
dpkg -s meshlab | grep Version
Version: 1.3.2+dfsg1-2build4
```

I don't see any .ogg files in ModelNet, I just see .off files. I have no idea what the problem you've got exactly.

**Comment by dmasmont** [comment]
Hello @wangg12 , it was a typo, I meant .off files.
I have figured out the error. Somehow in every .off file the first line break was missing.
